### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by awikkerink** [comment]
npm install silently ignores packages without a version. This has been bugging me for a while, and while there are workarounds, this will remove a lot of hassle.

**Comment by awikkerink** [comment]
ping @dlockhart

**Comment by awikkerink** [comment]
Could you merge? I don't have write permissions

**Comment by awikkerink** [comment]
@ryantmer could you also add a new tag for v3.0.4?

**Comment by ryantmer** [comment]
Done! Yeah I probably should have done that at the same time, whoops.

**Pull request merged**
