### PR TITLE
US92183 Remove window from behavior

### PR DESCRIPTION
**Pull request by svanherk**
I've seen Dave doing this in his cleanup steps, but this will cause the previous PR to be a breaking change and there's a few repos that use it other than `course-image`.  I don't think the other PR is breaking right now, but let me know if I'm missing something.

Not sure which is preferred: 
- To make the previous change a minor version and this a major version change
- Just merge this into the other PR and make that a major version change
- Not worry about this right now

### CODE REVIEW

**Comment by dlockhart** [comment]
Maybe this won't be a breaking change since `window` is implicit? But if we wanted to align the namespace with other behaviours under `D2L.PolymerBehaviors.*` then yeah that'd be breaking for sure.

**Comment by svanherk** [comment]
> Maybe this won't be a breaking change since window is implicit? But if we wanted to align the namespace with other behaviours under D2L.PolymerBehaviors.* then yeah that'd be breaking for sure.

I think Dave B said the linter might complain and fail builds.  And then if it's breaking anyways, I can align it under that namespace if that's something we want to do.  I'm not familiar with the behaviors yet, would this be helpful towards the Polymer 2 goal of using mixins?

**Comment by dlockhart** [comment]
Ah, so maybe the linter in the _other_ repos might hate it. Yeah OK, I'm good with combining this with aligning it under the `D2L.PolymerBehaviors.` namespace and a major version bump. Looks like it's used by: `course-image`, `user-profile-behavior`, `image-selector`, `image-banner-overlay`, `user-tile` and `my-courses`. So a lot of things we're going to be fixing up shortly anyway.

**Comment by svanherk** [comment]
Updated to move the behavior into the `D2L.PolymerBehaviors.*` namespace.

**Pull request merged**
